#!/usr/bin/env bash
#This is a script that does something#
for (( i=1 ; i<=100 ; i++))
do 
	if [ $(( i % 3 )) == 0 ] ; then 
		if [ $(( i % 5 )) == 0 ] ; then
			echo "FizzBuzz"
		else 
			echo "Fizz"
		fi
	else 
		if [ $(( i % 5 )) == 0 ] ; then 
			echo "Buzz"
		else 
			echo "$i"
	fi
	fi

done
