#!/usr/bin/env bash
#This is a script that does something#
for (( i=1 ; i<100 ; i++))
do 
	if [ $(( $i % 3 )) == 0 ] ; then 
		if [ $(( $i % 5 )) == 0 ] ; then
			echo "fizzbuzz"
		else 
			echo "fizz"
		fi
	else 
		if [ $(( $i % 5 )) == 0 ] ; then 
			echo "buzz"
		else 
			echo "$i"
	fi
	fi

done
