#!/usr/bin/env bash
#This is a script that does something#
i=$((1))
while [ $i -le 10 ];
do  
if [ $i = 4 ] ; then 
echo Bad luck

elif [ $i -eq 8 ]; then
echo Good luck
	
else 
	echo Best School 
fi
i=$((i + 1))
done
