#!/usr/bin/env bash
#This is a script that does something#
filename=school
if [ -f $filename ] ; then
	echo "${filename} file exist"
	echo "${filename} is a regular file"
	if [ -s $filename ] ; then
	
		echo "${filename} is not empty"
		else 
			echo "${filename} is empty"
	fi
else
	
if [ -d $filename ] ; then
	echo "${filename} exist"
	if [ $(ls -A $filename) ] ; then
	echo "${filename} is not empty"
else
	echo "${filename} is empty"
fi
else
	echo "${filename} does not exist"

fi
fi
