#!/usr/bin/env bash
#This is a script that does something useful#
# shellcheck disable=SC2009
echo "$$" > /var/run/myscript.pid
while (true);
do
	trap "echo I hate the kill command ; rm /var/run/myscript.pid ; exit" 15
	trap "echo Y U no love me?! ; exit" 2
	trap "rm /var/run/myscript.pid ; exit" 3
echo To infinity and beyond
sleep 2
done
