#!/usr/bin/env bash
#This is a script that does something useful#
# shellcheck disable=SC2009
case $1 in
	start)
	
	./manage_my_process &
	pgrep -f "./manage_my_process" > /var/run/my_process.pid 
	echo "manage_my_process started"
;;
	stop)
	pkill -f "./manage_my_process"
	
	sudo rm /var/run/my_process.pid

	echo "manage_my_process stopped"
;;
	restart)
	pkill -f "./manage_my_process"

	sudo rm /var/run/my_process.pid
	sleep 2	
	./manage_my_process &

	pgrep -f "./manage_my_process" > /var/run/my_process.pid
	echo "manage_my_process restarted"

;;
	*)
	echo "Usage: manage_my_process {start|stop|restart}"
;;	
	esac
